### ISSUE TITLE
Stats collection

### ISSUE THREAD

**Issue by sonal1204** [netmod-wg/acl-model#11]
Dataplane stats are gathered in a variety of ways. For e.g. dataplace could gather stats only per interface, per interface per ACL, aggregated over all interfaces, per ACE, per ACE per interface. The model currently doe snot have the capability to reflect this.

**Comment by elear** [comment]
Stats collection is a working group effort unto itself.  This should not be in the base model.

**Comment by einarnn** [comment]
I tend to agree with this perspective. We have many discussions on just this on different platforms.
