### ISSUE TITLE
ACL yang model does not define application of ACL(s) to an interface

### ISSUE THREAD

**Issue by sonal1204** [netmod-wg/acl-model#12]
Currently, the yang model does not define the application of an ACL to an interface. Different platforms can also support multiple ACL's on an interface. ACL's should be supported as a list in both ingress and egress directions.

**Comment by elear** [comment]
ACLs may apply things other than interfaces.  For example, in the case of MUD, it describes a packet flow that may be enforced at various points (a session, an interface, etc).  ACLs are better referenced off those models.

**Comment by einarnn** [comment]
Per above comment, ACLs are used far beyond just interface. I also think that we will end up in a lot of discussion on how this relates to the input interface match leaf. This is a twisty maze of passages. Do you think it's possible to articulate a simple, pervasive attachment model across vendors?

**Comment by sonal1204** [comment]
Added the interface support for the ACL for ingress and egress ACL's.
