### ISSUE TITLE
logging actions lacks a default value

### ISSUE THREAD

**Issue by mjethanandani** [netmod-wg/acl-model#14]
The current logging action does not define a default value. As defined it is not clear what the implication of not setting the leaf would be. The change is to add a default statement and set it to false to indicate that no logging action will be taken by default.

**Comment by mjethanandani** [comment]
Added a 'default "false"' statement for the logging action.

**Comment by plajjan** [comment]
Have you pushed this? I can't see any default statement in current master.

**Comment by mjethanandani** [comment]
It is not in the model that is in github. It is still in my local copy. And yes, have added default 'false' to logging to disable logging by default.

**Comment by plajjan** [comment]
Would it not be useful to push ASAP so we can discuss the most current version? :)

**Comment by mjethanandani** [comment]
Added 'default false' to logging.
