### ISSUE TITLE
Can "access-lists" be set up as a "grouping"

### ISSUE THREAD

**Issue by mrdeep1** [netmod-wg/acl-model#22]
Would it be possible to set up "access-lists" to be redefined as a "grouping", and then have 

container access-lists {
  description
    "This is a top level container for Access Control Lists.
       It can have one or more Access Control Lists as
       as defined in the grouping "access-lists".";
  uses access-lists;
}

This then give the flexibility of other YANG data models to make use of access-lists as a subset of a bigger data model

**Comment by mjethanandani** [comment]
Closed with the observation that "access-lists" should not be made a grouping, per the discussion on the mailing list [here](https://www.ietf.org/mail-archive/web/netmod/current/msg19942.html), and that LNE or schema mount should solve that problem.
