### ISSUE TITLE
Source/dest ports should contain an operator field

### ISSUE THREAD

**Issue by sonal1204** [netmod-wg/acl-model#6]
The source and destination ports should contain an operator field which can have values of lt, gt, eq, neq and range.

**Comment by mjethanandani** [comment]
The current model defines lower-port and upper-port with upper-port >= lower-port.  The range is implicit when both the lower-port and upper-port is specified. But the other operators required for specifying a rule need to be added.

**Comment by mjethanandani** [comment]
ACL rules for ports can include operators like lt (less than), gt (greater than), eq (equal), neq (not equal) and range to further describe the ports. The current model defines a lower and an upper port, which when both exist define the range. But the rest of the operators need to be defined. Those operators can only exist if one of the ports has been defined. To enable this, the following additions will be made to the model.

First a typedef for the different operators.
 ```
 /*
   * Typedefs
   */
  typedef operator {
    type enumeration {
      enum lt {
        description
          "Less than.";
      }
      enum gt {
        description
          "Greater than.";
      }
      enum eq {
        description
          "Equal to.";
      }
      enum neq {
        description
          "Not equal to.";
      }
    }
  }
```

and then the following addition to both the source-port-range and destination-port-range container.

```
      leaf opearation {
        type operator;
        must "(lower-port and not(upper-port)) or " +
        				"(not(lower-port) and (upper-port))";
        description
          "Operator to be applied on either the lower-port or
           upper-port.";
      }
```

**Comment by elear** [comment]
Should there also be lte and gte because people think in terms of a starting point in a range?  And is this actually required, given the existence of range?

**Comment by mjethanandani** [comment]
Added operator lte and gte. And yes, these operators are required. Note, the operator needs to be specified only if lower-port is defined. If both lower-port and upper-port are defined, it implies a range.

**Comment by elear** [comment]
Mahesh, can you explain the difference between this and range?

**Comment by mjethanandani** [comment]
There is no difference. But rather than requiring user to configure a range operator, the model says that if the user has defined both the lower-port and upper-port, then the model will assume it to be **the** port range.

**Comment by mjethanandani** [comment]
Implemented the above suggested solution.
