### ISSUE TITLE
dscp missing as a match criteria

### ISSUE THREAD

**Issue by sonal1204** [netmod-wg/acl-model#8]
The model is missing "dscp" attribute in the match criteria.

**Comment by mjethanandani** [comment]
This is currently defined as a 'tos' field of size uint8. Do we want to replace it with dscp-ecn?

**Comment by mjethanandani** [comment]
Replaced tos field with the following:

```
    ```
leaf dscp {
      type uint8 {
        range 0..63;
      }
      description
        "Also known as Traffic Class in IPv6. The Diffrentiated
         Services Code Point (DSCP) provides an indication of 
         the abstract parameters of the quality of service desired.";
      reference
        "RFC 2474.";
    } 
    leaf ecn {
      type uint8 {
        range 0..3;
      }
      description
        "Explicit Congestion Notification.";
      reference
        "RFC 3168.";
    }
```
```

**Comment by mjethanandani** [comment]
Implemented the above suggested solution.
