### ISSUE TITLE
Precedence missing in model

### ISSUE THREAD

**Issue by sonal1204** [netmod-wg/acl-model#9]
Precedence does not appear as a match criteria in the model.

**Comment by mjethanandani** [comment]
Again, this has been defined as part of 'tos' field in the IP header of size uint8. This also conflicts with the other requirement to specify dscp. We can leave it as a tos field as it is currently defined, or we could replace it with dscp/ecn. What is the preference?

**Comment by einarnn** [comment]
Precedence field is deprecated, isn't it?

**Comment by mjethanandani** [comment]
Yes, it is if you consider that most machines support dscp/ecn field.

**Comment by mjethanandani** [comment]
Since precedence is deprecated, will close this issue.
